---
title: "analysis_empirical"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
```


```{r}

knitr::opts_knit$set(root.dir = "~/Advanced_Cognitive_Modelling_2026/4_")

```


```{r}
#load data
#data <- read_csv("C:/Users/anelo/OneDrive/Documents/Advanced_Cognitive_Modelling_2026/4_/data/AlienData.txt")

data <- read_csv("~/Advanced_Cognitive_Modelling_2026/4_/data/AlienData.txt")



```


```{r}

#in response column, 1 and 2 are 0(no danger) and 3 and 4 are 1(danger)
data <- data %>% 
  mutate(response = ifelse(response %in% c(1, 2), 0, 1))

#keep only session 1 and condition 1
data <- data %>% 
  filter(session == 1 & condition == 1)




#calculating cumulative win rate
cumulative_win_df <- data %>%
  filter(subject == 1) %>%
  mutate(cumulative_correct = cumsum(correct) / trial)



```


```{r}

# #calculating cumulative win rate
# cumulative_win_df <- data %>%  
#   mutate(cumulative_correct = cumsum(correct)/trial)




```



```{r}
#plot of win over time


wins <- ggplot(cumulative_win_df, aes(x = trial)) + 
  
  geom_line(aes(y = cumulative_correct, color = "Cumulative wins")) +
  geom_point(aes(y = correct, color = factor(correct)), alpha = 0.6) +
  
  #geom_point(aes(y = dangerous, color = "Dangerous"), alpha = 0.6) +
  
  #geom_line(aes(y = response, color = "Response"), linetype = "dashed") +
  
  
  #geom_point(aes(y = response, color = factor(correct)), alpha = 0.6) +
  

  geom_hline(yintercept = 0.5, linetype = "solid", alpha = 0.5) +
  
  ylim(0, 1) +
  theme_classic() +
  
  scale_color_manual(
    name = "Legend",
    values = c(
      "Cumulative wins" = "darkgreen", 
      "0" = "red",
      "1" = "green"),
      #"Correct guess" = "green"), 
      #  "Dangerous" = "red", 
      #  "Response" = "blue"), 
  
     
  labels = c(
      "Cumulative wins" = "Cumulative wins",
      "0" = "Wrong guess",
      "1" = "Correct guess"
    )
    

  ) + 
  
  labs(
    title = "Performance over trials",
    x = "Trial Number",
    y = "Proportion Correct"
)


wins





  geom_line(aes(y = cumulative_accuracy, color = "Cumulative Accuracy")) +
  geom_point(aes(y = correct, color = "Correct/Incorrect"), alpha = 0.6) +
  geom_line(aes(y = cumulative / max(cumulative, na.rm = TRUE), 
                color = "Cumulative Score (normalized)"), linetype = "dashed") +
  

```




```{r}

# check if cumulative_correct has valid values
head(cumulative_win_df$cumulative_correct)
sum(is.na(cumulative_win_df$cumulative_correct))
nrow(cumulative_win_df)

head(cumulative_win_df$trial, 200)

```



```{r}


## kopi af assignment 1 plots

rlr_winner_dynamic_zoom <- ggplot(filtered3, aes(x = trial)) + 
  
  geom_line(aes(y = choicesA, color = "Choice RL-R"), linetype = "dotted", alpha = .8) +
  geom_line(aes(y = choicesB, color = "Choice WSLS"), linetype = "dotted", alpha = .8) +
  geom_point(aes(y = winA, color = "Win/Loss (RL-R)")) +
  geom_line(aes(y = cumulativeWinA, color = "Cumulative Win (RL-R)")) +
  geom_line(aes(y = losingA, color = "'Losing' mode (RL-R)"), linetype = "dashed") +
  
  geom_hline(yintercept = 0.5) +
  ylim(0, 1) +
  xlim(0, 30) +
  theme_classic() +
  
  scale_color_manual(
    name = "Legend",
    values = c(
      "Choice RL-R" = "blue",
      "Choice WSLS" = "red",
      "Win/Loss (RL-R)" = "green",
      "Cumulative Win (RL-R)" = "darkgreen",
      "'Losing' mode (RL-R)" = "orange"
    )
  ) +
  labs(
    title = "Agent pair 10: RL-R vs. WSLS",
    subtitle = "Example of RL-R winning game behaviour (zoomed in, 30 of 120 trials)",
    x = "Trial Number",
    y = "Average Proportion Wins"
  )
rlr_winner_dynamic_zoom
```

